name: "GitHub Actions Example"

"on":
  push: { branches: [main] }

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
      TF_WORKSPACE: my-workspace
      repository: https://github.com/adi658/samplenginx.wiki.git
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}
        env:
          TF_CLI_ARGS_init: "-backend-config=role_arn=arn:aws:iam::99999999:role/my-github-actions-role -upgrade -reconfigure"
          TF_VAR_assume_role: "my-github-actions-role"

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "my-github-actions-role"    

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{env.repository}}.wiki    # specify the wiki repo and push the update.
          github_token: ${{ secrets.PERSONAL_PAT }}
      
      
      
